// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw5nwiXEnEIUEkG0F3WfBzlxotbU27vqM',
    appId: '1:145299167499:web:286ca4bf63e175f2d1ea0e',
    messagingSenderId: '145299167499',
    projectId: 'jukeboxd-demo-3',
    authDomain: 'jukeboxd-demo-3.firebaseapp.com',
    databaseURL: 'https://jukeboxd-demo-3-default-rtdb.firebaseio.com',
    storageBucket: 'jukeboxd-demo-3.appspot.com',
    measurementId: 'G-1WNT9QXZNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA84wunnwO0KIPEswm-yw7aGtsy75HBwss',
    appId: '1:145299167499:android:17ac535d3a9c7350d1ea0e',
    messagingSenderId: '145299167499',
    projectId: 'jukeboxd-demo-3',
    databaseURL: 'https://jukeboxd-demo-3-default-rtdb.firebaseio.com',
    storageBucket: 'jukeboxd-demo-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn7rowDuz6LOmS8-sp7SYAmV93m7mOzAw',
    appId: '1:145299167499:ios:fbbf3c454d115500d1ea0e',
    messagingSenderId: '145299167499',
    projectId: 'jukeboxd-demo-3',
    databaseURL: 'https://jukeboxd-demo-3-default-rtdb.firebaseio.com',
    storageBucket: 'jukeboxd-demo-3.appspot.com',
    iosClientId: '145299167499-6eum7hms0tu7e96pkgoo4m27ekg2mkaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJukeboxDemo4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn7rowDuz6LOmS8-sp7SYAmV93m7mOzAw',
    appId: '1:145299167499:ios:81b3d5c422f9b7ead1ea0e',
    messagingSenderId: '145299167499',
    projectId: 'jukeboxd-demo-3',
    databaseURL: 'https://jukeboxd-demo-3-default-rtdb.firebaseio.com',
    storageBucket: 'jukeboxd-demo-3.appspot.com',
    iosClientId: '145299167499-vsiu1gphhl428rs8u5c7gq1f25f7pttj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJukeboxDemo4.RunnerTests',
  );
}
